---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.3.4
  amd64: ghcr.io/hassio-addons/debian-base:7.3.4

args:
  EXTENSIONS_GALLERY: >
    {"serviceUrl":"https://marketplace.visualstudio.com/_apis/public/gallery",
    "cacheUrl":"https://vscode.blob.core.windows.net/gallery/index",
    "itemUrl":"https://marketplace.visualstudio.com/items"}
